# Generated by Django 3.0.2 on 2021-02-10 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CsvImportado1',
            fields=[
                ('id', models.TextField(db_column='ID', primary_key=True, serialize=False)),
                ('grupo_asignado', models.TextField(db_column='Grupo_Asignado')),
                ('estado', models.TextField(db_column='Estado')),
                ('status_reason_hidden', models.TextField(db_column='Status_Reason_Hidden')),
                ('id_cliente', models.TextField(db_column='ID_Cliente')),
                ('razon_social', models.TextField(db_column='Razon_Social')),
                ('cliente_sidi', models.TextField(db_column='Cliente_SIDI')),
                ('ci', models.TextField(db_column='CI')),
                ('clase_ci', models.TextField(db_column='CLASE_CI')),
                ('fecha_envio', models.TextField(db_column='Fecha_Envio')),
                ('tipo_incidencia', models.TextField(db_column='Tipo_Incidencia')),
                ('segmento', models.TextField(db_column='Segmento')),
                ('n2_categ_prod', models.TextField(db_column='N2_Categ_Prod')),
                ('n3_categ_prod', models.TextField(db_column='N3_Categ_Prod')),
                ('n1_cat_ope', models.TextField(db_column='N1_Cat_Ope')),
                ('n2_cat_ope', models.TextField(db_column='N2_Cat_Ope')),
                ('n3_cat_ope', models.TextField(db_column='N3_Cat_Ope')),
                ('urgencia', models.TextField(db_column='Urgencia')),
                ('prioridad', models.TextField(db_column='Prioridad')),
                ('fecha_cierre', models.TextField(db_column='Fecha_Cierre')),
                ('assigned_company', models.TextField(db_column='Assigned_Company')),
                ('assigned_org', models.TextField(db_column='Assigned_Org')),
                ('usuario_asignado', models.TextField(db_column='Usuario_Asignado')),
                ('remitente', models.TextField(db_column='Remitente')),
                ('ultima_mod', models.TextField(db_column='Ultima_Mod')),
                ('celula_n', models.IntegerField(db_column='Celula_N')),
            ],
            options={
                'db_table': 'CSV_Importado1',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tablaseguimiento',
            fields=[
                ('orderid', models.AutoField(db_column='OrderId', primary_key=True, serialize=False)),
                ('detalle', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('reactivar', models.DateTimeField(blank=True, default=None, null=True)),
                ('prioridad', models.CharField(blank=True, choices=[('0', 'URGENTE'), ('1', 'PRIORITARIO'), ('2', 'NORMAL')], default='2', max_length=100, null=True)),
                ('tkt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tkt', to='pasaje.CsvImportado1')),
            ],
            options={
                'db_table': 'TablaSeguimiento',
                'managed': True,
            },
        ),
    ]
