# Generated by Django 3.0.2 on 2021-05-07 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CsvImportado1',
            fields=[
                ('id', models.TextField(db_column='ID', max_length=255, primary_key=True, serialize=False)),
                ('grupo_asignado', models.TextField(db_column='Grupo_Asignado')),
                ('estado', models.TextField(db_column='Estado')),
                ('status_reason_hidden', models.TextField(db_column='Status_Reason_Hidden')),
                ('id_cliente', models.TextField(db_column='ID_Cliente')),
                ('razon_social', models.TextField(db_column='Razon_Social')),
                ('cliente_sidi', models.TextField(db_column='Cliente_SIDI')),
                ('ci', models.TextField(db_column='CI')),
                ('clase_ci', models.TextField(db_column='CLASE_CI')),
                ('fecha_envio', models.TextField(db_column='Fecha_Envio')),
                ('tipo_incidencia', models.TextField(db_column='Tipo_Incidencia')),
                ('segmento', models.TextField(db_column='Segmento')),
                ('n2_categ_prod', models.TextField(db_column='N2_Categ_Prod')),
                ('n3_categ_prod', models.TextField(db_column='N3_Categ_Prod')),
                ('n1_cat_ope', models.TextField(db_column='N1_Cat_Ope')),
                ('n2_cat_ope', models.TextField(db_column='N2_Cat_Ope')),
                ('n3_cat_ope', models.TextField(db_column='N3_Cat_Ope')),
                ('urgencia', models.TextField(db_column='Urgencia')),
                ('prioridad', models.TextField(db_column='Prioridad')),
                ('fecha_cierre', models.TextField(db_column='Fecha_Cierre')),
                ('assigned_company', models.TextField(db_column='Assigned_Company')),
                ('assigned_org', models.TextField(db_column='Assigned_Org')),
                ('usuario_asignado', models.TextField(db_column='Usuario_Asignado')),
                ('remitente', models.TextField(db_column='Remitente')),
                ('ultima_mod', models.TextField(db_column='Ultima_Mod')),
                ('celula_n', models.IntegerField(db_column='Celula_N')),
            ],
            options={
                'db_table': 'CSV_Importado1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CsvImportado2',
            fields=[
                ('id', models.TextField(db_column='ID', max_length=255, primary_key=True, serialize=False)),
                ('grupo_asignado', models.TextField(db_column='Grupo_Asignado')),
                ('estado', models.TextField(db_column='Estado')),
                ('status_reason_hidden', models.TextField(db_column='Status_Reason_Hidden')),
                ('id_cliente', models.TextField(db_column='ID_Cliente')),
                ('razon_social', models.TextField(db_column='Razon_Social')),
                ('cliente_sidi', models.TextField(db_column='Cliente_SIDI')),
                ('ci', models.TextField(db_column='CI')),
                ('clase_ci', models.TextField(db_column='CLASE_CI')),
                ('fecha_envio', models.TextField(db_column='Fecha_Envio')),
                ('tipo_incidencia', models.TextField(db_column='Tipo_Incidencia')),
                ('segmento', models.TextField(db_column='Segmento')),
                ('n2_categ_prod', models.TextField(db_column='N2_Categ_Prod')),
                ('n3_categ_prod', models.TextField(db_column='N3_Categ_Prod')),
                ('n1_cat_ope', models.TextField(db_column='N1_Cat_Ope')),
                ('n2_cat_ope', models.TextField(db_column='N2_Cat_Ope')),
                ('n3_cat_ope', models.TextField(db_column='N3_Cat_Ope')),
                ('urgencia', models.TextField(db_column='Urgencia')),
                ('prioridad', models.TextField(db_column='Prioridad')),
                ('fecha_cierre', models.TextField(db_column='Fecha_Cierre')),
                ('assigned_company', models.TextField(db_column='Assigned_Company')),
                ('assigned_org', models.TextField(db_column='Assigned_Org')),
                ('usuario_asignado', models.TextField(db_column='Usuario_Asignado')),
                ('remitente', models.TextField(db_column='Remitente')),
                ('ultima_mod', models.TextField(db_column='Ultima_Mod')),
                ('celula_n', models.IntegerField(db_column='Celula_N')),
            ],
            options={
                'db_table': 'CSV_Importado2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Eventostkt',
            fields=[
                ('sk', models.AutoField(db_column='SK', primary_key=True, serialize=False)),
                ('id', models.CharField(blank=True, db_column='ID', max_length=250, null=True)),
                ('grupo_asignado', models.CharField(blank=True, db_column='Grupo_Asignado', max_length=250, null=True)),
                ('grupo_asignado_anterior', models.CharField(blank=True, db_column='Grupo_Asignado_anterior', max_length=250, null=True)),
                ('estado', models.CharField(blank=True, db_column='Estado', max_length=250, null=True)),
                ('estado_anterior', models.CharField(blank=True, db_column='Estado_anterior', max_length=250, null=True)),
                ('status_reason_hidden', models.CharField(blank=True, db_column='Status_Reason_Hidden', max_length=250, null=True)),
                ('status_reason_hidden_anterior', models.CharField(blank=True, db_column='Status_Reason_Hidden_anterior', max_length=250, null=True)),
                ('tipo_incidencia', models.CharField(blank=True, db_column='Tipo_Incidencia', max_length=250, null=True)),
                ('tipo_incidencia_anterior', models.CharField(blank=True, db_column='Tipo_Incidencia_anterior', max_length=250, null=True)),
                ('fecha_envio', models.CharField(blank=True, db_column='Fecha_Envio', max_length=250, null=True)),
                ('tiempo_acumulado', models.CharField(blank=True, db_column='Tiempo_Acumulado', max_length=250, null=True)),
                ('horario', models.DateTimeField(db_column='Horario')),
            ],
            options={
                'db_table': 'eventostkt',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Llamadas',
            fields=[
                ('id_llamadas', models.AutoField(db_column='ID_Llamadas', primary_key=True, serialize=False)),
                ('encola', models.IntegerField(db_column='EnCola')),
                ('aux', models.IntegerField(db_column='AUX')),
                ('presentes', models.IntegerField(db_column='Presentes')),
                ('disponibles', models.IntegerField(db_column='Disponibles')),
                ('enllamada', models.IntegerField(db_column='EnLlamada')),
                ('acw', models.IntegerField(db_column='ACW')),
                ('otros', models.IntegerField(db_column='Otros')),
                ('hora', models.TextField(db_column='Hora')),
                ('otro', models.IntegerField()),
                ('ring', models.IntegerField(db_column='Ring')),
            ],
            options={
                'db_table': 'Llamadas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Llamadasssdd',
            fields=[
                ('id_llamadas', models.AutoField(db_column='ID_Llamadas', primary_key=True, serialize=False)),
                ('encola', models.IntegerField(db_column='EnCola')),
                ('aux', models.IntegerField(db_column='AUX')),
                ('presentes', models.IntegerField(db_column='Presentes')),
                ('disponibles', models.IntegerField(db_column='Disponibles')),
                ('enllamada', models.IntegerField(db_column='EnLlamada')),
                ('acw', models.IntegerField(db_column='ACW')),
                ('otros', models.IntegerField(db_column='Otros')),
                ('hora', models.TextField(db_column='Hora')),
                ('otro', models.IntegerField()),
                ('ring', models.IntegerField(db_column='Ring')),
            ],
            options={
                'db_table': 'LlamadasSSDD',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tablaseguimiento',
            fields=[
                ('orderid', models.AutoField(db_column='OrderId', primary_key=True, serialize=False)),
                ('detalle', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('reactivar', models.DateField(blank=True, default=None, null=True)),
                ('reactivar_hora', models.TimeField(blank=True, null=True)),
                ('prioridad', models.CharField(blank=True, choices=[('0', 'URGENTE'), ('1', 'PRIORITARIO'), ('2', 'NORMAL')], default='2', max_length=100, null=True)),
                ('tkt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tkt', to='pasaje.CsvImportado1')),
            ],
            options={
                'db_table': 'TablaSeguimiento',
                'managed': True,
            },
        ),
    ]
