# Generated by Django 3.0.2 on 2021-02-22 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasaje', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablaseguimiento',
            name='reactivar_hora',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tablaseguimiento',
            name='reactivar',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
